core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this



urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls")), 


]

apps/home/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone
import schedule
import time
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType



from datetime import datetime, date
from django.dispatch import receiver
from django.db.models.signals import post_save

from datetime import timedelta










# Assurez-vous de créer d'autres autorisations pour d'autres vues (ajout, modification, suppression) si nécessaire.

# Assurez-vous de créer d'autres autorisations pour ajouter, modifier et supprimer si nécessaire.


class Categorie(models.Model):
    num_cat = models.CharField(max_length=3)

    def num_cat_to_roman(self):
        # Dictionnaire pour mapper les chiffres arabes aux chiffres romains
        roman_numerals = {
            1: "I",
            2: "II",
            3: "III",
            4: "IV",
            5: "V",
            6: "VI",
            7: "VII",
            8: "VIII",
            9: "IX",
            10: "X",
            # Ajoutez plus de correspondances ici si nécessaire
        }

        # Assurez-vous que le champ `num_cat` contient une valeur numérique valide
        try:
            num = int(self.num_cat)
        except ValueError:
            return self.num_cat  # Si ce n'est pas un nombre, renvoyez la valeur d'origine

        # Vérifiez si le nombre est dans le dictionnaire
        if num in roman_numerals:
            return roman_numerals[num]

        return self.num_cat  # Si le nombre n'a pas de correspondance, renvoyez la valeur d'origine

    def __str__(self):
        return self.num_cat_to_roman()



class Diplome(models.Model):
    type_dip = models.CharField(max_length=25)
    description = models.TextField(null=True, blank=True)




    

class Contrat(models.Model):
    type_con = models.CharField(max_length=30)
    dure_con = models.IntegerField(null=False)


def validate_digit_1_to_3(value):
    if len(value) != 1 or value not in ('1', '2', '3'):
        raise ValidationError('Ce champ doit contenir les chiffres 1, 2 ou 3.')

class Grade(models.Model):
    num_classe = models.CharField(max_length=1, validators=[validate_digit_1_to_3])
    num_echellon = models.CharField(max_length=1, validators=[validate_digit_1_to_3])
def get_grade_display(self):
    return f'{self.num_classe}C{self.num_echellon}E'
    
    




class Domaine(models.Model):
    nom_dom = models.CharField(max_length=50)
    description = models.TextField(max_length=50, null=True, blank=True)





class Departement(models.Model):
    nom_dep = models.CharField(max_length=25)
    description = models.TextField(max_length=100, null=True, blank=True)
   


    
    

def age_validator(value):
    if not 10 <= int(value) <= 99:
        raise ValidationError('L\'âge doit être composé de deux chiffres.')

def im_validator(value):
    if not value.isdigit() or len(value) != 6:
        raise ValidationError('Le numéro matricule doit contenir exactement 6 chiffres.')

def cin_validator(value):
    if not value.isdigit() or len(value) != 12:
        raise ValidationError('Le numéro CIN doit contenir exactement 12 chiffres.')

def num_tel_validator(value):
    if not value.isdigit() or len(value) != 10:
        raise ValidationError('Le numéro de téléphone doit contenir exactement 10 chiffres.')

def indice_validator(value):
    if not value.isdigit() or len(value) != 6:
        raise ValidationError('L\'indice doit être composé de six chiffres.')



 




  


class Fonction(models.Model):
    nom_fc = models.CharField(max_length=30)

class Mention(models.Model):
    nom_me = models.CharField(max_length=30)
    description = models.TextField(null=True, blank=True)

class Corps(models.Model):
    nom_cr = models.CharField(max_length=25)
    description = models.TextField(null=True, blank=True)

class Situation(models.Model):
    type_st = models.CharField(max_length=25)  # Exemple de champ de type CharField

    def __str__(self):
        return self.type_st



class Enseignant(models.Model):
    nom_en = models.CharField(max_length=30)
    prenom_en = models.CharField(max_length=30, null=True, blank=True)
    age = models.IntegerField()
    adress = models.TextField(default="Maninday")
    SEX_CHOICES = [
        ('M', 'Masculin'),
        ('F', 'Féminin'),
    ]
    sex = models.CharField(max_length=1, choices=SEX_CHOICES)
    num_tel = models.CharField(max_length=10, validators=[num_tel_validator], null=True)
    cin = models.CharField(max_length=12, validators=[cin_validator], null=True, unique=True)
    indice = models.CharField(max_length=6, null=True)
    im = models.CharField(max_length=6, unique=True)  # Numéro matricule
    date_nais = models.DateField()
    date_PF = models.DateField()
    image = models.ImageField(upload_to='enseignant_images/', null=True, blank=True)
    grade = models.ForeignKey('Grade', on_delete=models.CASCADE)
    diplome = models.ForeignKey('Diplome', on_delete=models.CASCADE)
    corps = models.ForeignKey('Corps', on_delete=models.CASCADE, null=True)
    situation = models.ForeignKey('Situation', on_delete=models.CASCADE) # Champ pour la situation
    mention = models.ForeignKey('Mention', on_delete=models.CASCADE, null=True)
    domaine = models.ForeignKey('Domaine', on_delete=models.CASCADE, null=True)
    departement = models.ForeignKey('Departement', on_delete=models.CASCADE, null=True)



    def get_image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return ''
    


    def validate_im(self):
        if len(self.im) != 6 or not self.im.isdigit():
            raise ValidationError('Le numéro matricule doit contenir exactement 6 chiffres.')

    def validate_age(self):
        if not 10 <= self.age <= 99:  # Vérifie que l'âge est composé de deux chiffres.
            raise ValidationError('L\'âge doit être composé de deux chiffres.')

    def save(self, *args, **kwargs):
        self.validate_im()  # Appeler la validation du numéro matricule
        self.validate_age()  # Appeler la validation de l'âge

        # Vérifier si l'âge est de 60 ans ou plus
    


        super(Enseignant, self).save(*args, **kwargs)
    
    



    
   






class Employe(models.Model):
    nom_em = models.CharField(max_length=30)
    prenom_em = models.CharField(max_length=30, null=True, blank=True)
    age = models.PositiveSmallIntegerField()
    adresse = models.TextField(default="Maninday") # Corrected "adress_em" to "adresse"
    sex = models.CharField(max_length=1, choices=[('M', 'Masculin'), ('F', 'Féminin')])
    im = models.CharField(max_length=6, unique=True)
    date_nais = models.DateField()
    date_PF = models.DateField(null=True, blank=True)
    cin = models.CharField(max_length=12, unique=True)
    num_tel = models.CharField(max_length=10)
    image = models.ImageField(upload_to='employe_photos/', null=True, blank=True)
    indice = models.CharField(max_length=6)
    categorie = models.ForeignKey(Categorie, on_delete=models.CASCADE)
    diplome = models.ForeignKey(Diplome, on_delete=models.CASCADE)
    contrat = models.ForeignKey(Contrat, on_delete=models.CASCADE)
    situation = models.ForeignKey(Situation, on_delete=models.CASCADE)
    domaine = models.ForeignKey(Domaine, on_delete=models.CASCADE)
    departement = models.ForeignKey(Departement, on_delete=models.CASCADE)
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE)
    fonction = models.ForeignKey(Fonction, on_delete=models.CASCADE, null=True, blank=True)
 

    class Meta:
        verbose_name = "Employé"
        verbose_name_plural = "Employés"  
    def get_image_url(self):
        if self.image:
            return self.image.url
        else:
            return ''




class Affectation(models.Model):
    employe = models.ForeignKey(Employe, on_delete=models.CASCADE)
    date_aff = models.DateField()
    motif = models.TextField()
    n_domaine = models.ForeignKey(Domaine, on_delete=models.CASCADE)
    n_departement = models.ForeignKey(Departement, on_delete=models.CASCADE)
    n_fonction = models.ForeignKey(Fonction, on_delete=models.CASCADE)
@receiver(post_save, sender=Affectation)
def update_employee_info(sender, instance, created, **kwargs):
    if created:  # Vérifie si c'est une nouvelle affectation
        employe = instance.employe
        employe.domaine = instance.n_domaine
        employe.departement = instance.n_departement
        employe.fonction = instance.n_fonction
        employe.save()
   
  


class TypeConge(models.Model):
    nom_tc = models.CharField(max_length=40)
    nb_jour = models.IntegerField(default=0)





class Conge(models.Model):
    date_debut = models.DateField()
    date_fin = models.DateField()
    type_conge = models.ForeignKey(TypeConge, on_delete=models.CASCADE)
    employe = models.ForeignKey(Employe, on_delete=models.CASCADE, null=True, blank=True)
    enseignant = models.ForeignKey(Enseignant, on_delete=models.CASCADE, null=True, blank=True)
    jours_utilises = models.PositiveIntegerField(null=True, default=0)
    jours_restants = models.PositiveIntegerField(null=True, default=0)  # Ajustez la valeur par défaut

    def save(self, *args, **kwargs):
        if self.date_debut and self.type_conge:
            
            if isinstance(self.date_debut, str):
                self.date_debut = datetime.strptime(self.date_debut, '%Y-%m-%d').date()

            if isinstance(self.date_fin, str):
                self.date_fin = datetime.strptime(self.date_fin, '%Y-%m-%d').date()

            aujourdhui = date.today()

            if self.date_debut > aujourdhui:  # Si la date de début est dans le futur
                self.jours_utilises = 0
                self.jours_restants = 0
            elif self.date_fin and self.date_fin > self.date_debut:
                # Calcul des jours utilisés jusqu'à la date actuelle

apps/templates/enseignants/enseignant_profile.html
{% extends 'layouts/base.html' %}

{% block title %} Profile {% endblock title %}

{% block content %}

<div class="header pb-6 d-flex align-items-center" 
     style="min-height: 400px; background-image: url('{{ enseignant.image.url }}') ; background-size: cover; background-position: center top;">
  <!-- Mask -->
  <span class="mask bg-gradient-default opacity-8"></span>
  <!-- Header container -->
  <div class="container-fluid d-flex align-items-center">
    <div class="row">
      <div class="col-lg-7 col-md-10">
        <h1 class="display-2 text-white"> 
          {{ enseignant.nom_en }} {{ enseignant.prenom_en }}
        </h1>
        
      
      </div>
    </div>
  </div>
</div>

<!-- Page content -->
<div class="container-fluid mt--6">
  <div class="row">
    <div class="col-xl-4 order-xl-2">
      <div class="card card-profile">
        <img src="/static/assets/img/theme/img-1-1000x600.jpg" alt="Image placeholder" class="card-img-top">
        <div class="row justify-content-center">
          <div class="col-lg-3 order-lg-2">
            <div class="card-profile-image">
              <a href="#">
                <img src="{{ enseignant.image.url }}" class="rounded-circle">
              </a>
            </div>
          </div>
        </div>
        <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
          
        </div>
        <div class="card-body pt-0">
          <div class="row">
            <div class="col">
              <div class="card-profile-stats d-flex justify-content-center">
                <div>
                  
                </div>
              </div>
            </div>
          </div>
          <div class="text-center">
            <h5 class="h3">
              {{ enseignant.nom_en}} {{ enseignant.prenom_en }}
            </h5>
            <div class="h5 font-weight-300">
              {{ enseignant.age }} ans
            </div>
            <div class="h5 mt-4">
              <i class="ni business_briefcase-24 mr-2"></i>{{ enseignant.mention.nom_me }}
            </div>
            <div>
              <i class="ni education_hat mr-2"></i>{{ enseignant.departement.nom_dep }}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-8 order-xl-1">
      <div class="card">
        <div class="card-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h3 class="mb-0">Profil de  {{ enseignant.nom_en }} {{ enseignant.prenom_en }} </h3>
            </div>
           
          </div>
        </div>
        <div class="card-body">
          <h6 class="heading-small text-muted mb-4">Informations  Personnelle</h6>
          <div class="pl-lg-4">
            <div class="row">
              <div class="col-lg-4">
                <div class="form-group text-center">
                  <label class="form-control-label" for="nom_en">Nom</label>
                  <p>{{ enseignant.nom_en }}</p>
                </div>
              </div>
              <div class="col-lg-4">
                <div class="form-group text-center">
                  <label class="form-control-label" for="prenom_en">Prénom</label>
                  <p>{{ enseignant.prenom_en }}</p>
                </div>
              </div>
              <div class="col-lg-2">
                <div class="form-group text-center">
                  <label class="form-control-label" for="age">Age</label>
                  <p>{{ enseignant.age }} ans</p>
                </div>
              </div>
             
            </div>
            <div class="row">
             <div class="col-lg-3">
                <div class="form-group text-center">
                  <label class="form-control-label" for="sex">Sexe</label>
                  <p>{{ enseignant.get_sex_display }}</p>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group text-center">
                  <label class="form-control-label" for="adress">Adresse</label>
                  <p>{{ enseignant.adress }}</p>
                </div>
              </div>
               <div class="col-md-3">
                <div class="form-group text-center">
                  <label class="form-control-label" for="cin">CIN</label>
                  <p>{{ enseignant.cin }}</p>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group text-center">
                  <label class="form-control-label" for="num_tel">Numero Telephone</label>
                  <p>{{ enseignant.num_tel }}</p>
                </div>
              </div>
            </div>
            <!-- Continuez à ajouter d'autres attributs de l'employé ici -->
          </div>
          <hr class="my-4" />
          <!-- Adresse -->
          <h6 class="heading-small text-muted mb-4">Informations  proffetionnelle</h6>
          <div class="pl-lg-4">
            <div class="row">
              <div class="col-md-3">
                <div class="form-group text-center">
                  <label class="form-control-label" for="im">Numero Matricule</label>
                  <p>{{ enseignant.im }}</p>
                </div>
              </div>

              <div class="col-md-3">
                <div class="form-group text-center">
                  <label class="form-control-label" for="date_PF">Date Prise de Fonction</label>
                  <p>{{ enseignant.date_PF }}</p>
                </div>
              </div>

              <div class="col-md-3">
                <div class="form-group text-center">
                  <label class="form-control-label" for="indice">Indice</label>
                  <p>{{ enseignant.indice }}</p>
                </div>
              </div>

              <div class="col-md-3">
                <div class="form-group text-center">
                  <label class="form-control-label" for="diplome">Diplome</label>
                  <p>{{ enseignant.diplome.type_dip }}</p>
                </div>
              </div>
              



            </div>
            <div class="row">
              

              <div class="col-md-3">
                <div class="form-group text-center">
                  <label class="form-control-label" for="departement">Departement</label>
                  <p>{{ enseignant.departement.nom_dep }}</p>
                </div>
              </div>

              <div class="col-md-3">
                <div class="form-group text-center">
                  <label class="form-control-label" for="domaine">Domaine</label>
                  <p>{{ enseignant.domaine.nom_dom }}</p>
                </div>
              </div>

               <div class="col-md-3">
                <div class="form-group text-center">
                  <label class="form-control-label" for="situation">Situation</label>
                  <p>{{ enseignant.situation.type_st }}</p>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group text-center">
                  <label class="form-control-label" for="mention">Mention</label>
                  <p>{{ enseignant.mention.description }}</p>
                </div>
              </div>

             

              
              <div class="col-md-3">
                <div class="form-group text-center">
                  <label class="form-control-label" for="grade">Grade</label>
                  <p>{{ enseignant.grade.num_classe }}C{{ enseignant.grade.num_echellon }}E</p>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group text-center">
                  <label class="form-control-label" for="corps">Corps</label>
                  <p>{{ enseignant.corps.description }}</p>
                </div>
              </div>



            </div>
            <!-- Continuez à ajouter d'autres informations de contact ici -->
          </div>
          
         
        </div>
      </div>
    </div>
    
    
    <!-- ... (le reste du contenu reste inchangé) ... -->
    

  </div>
  

  {% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}{% endblock javascripts %}

apps/templates/enseignants/liste_enseignants.html
{% extends 'layouts/base.html' %}

{% block title %} Profile {% endblock title %}

{% block content %}
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Search form -->
    

    <form class="navbar-search navbar-search-light form-inline mr-sm-3">
      {% csrf_token %}
      <div class="form-group mb-0">
          <div class="input-group input-group-alternative input-group-merge">
              <div class="input-group-prepend">
                  <span class="input-group-text"><i class="fas fa-search"></i></span>
              </div>
              <input class="form-control" id="searchInput"  placeholder="Search" >
          </div>
      </div>
      <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
          <span aria-hidden="true">×</span>
      </button>
  </form>
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
            <i class="ni ni-zoom-split-in"></i>
          </a>
        </li>
      
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-ungroup"></i>
          </a>
          
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-dark bg-default  dropdown-menu-right ">
            <div class="row shortcuts px-4">
              <a href="{% url 'liste_employes' %}" class="col-4 shortcut-item text-center">
                <span class="shortcut-media avatar rounded-circle bg-gradient-red">
                  <i class="fas fa-users"></i>
                </span>
                <small>P.A.T</small>
              </a>
              <a href="{% url 'liste_enseignants' %}" class="col-4 shortcut-item text-center">
                <span class="shortcut-media avatar rounded-circle bg-gradient-orange">
                  <i class="ni ni-hat-3"></i>
                </span>
                <small>MESupReS</small>
              </a>
             
              <a href="{% url 'liste_conges' %}" class="col-4 shortcut-item text-center">
                <span class="shortcut-media avatar rounded-circle bg-gradient-green">
                  <i class="ni ni-single-copy-04"></i>
                </span>
                <small>Conge</small>
              </a>
              <a href="{% url 'list_affectations' %}" class="col-4 shortcut-item text-center">
                <span class="shortcut-media avatar rounded-circle bg-gradient-purple">
                  <i class="ni ni-briefcase-24 "></i>
                </span>
                <small>Affectation</small>
              </a>
            </div>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              
              <div class="media-body  ml-2  d-none d-lg-block">
                <span class="mb-0 text-sm ">
                 
                  {{ request.user.username|upper }}
                
                </span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu  dropdown-menu-right ">
           
            <div class="dropdown-divider"></div>
            <a href="{% url 'logout' %}" class="dropdown-item">
              <i class="fas fa-sign-out-alt"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0">MESupReS</h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item"><a href="/"><i class="fas fa-home"></i></a></li>
              <li class="breadcrumb-item">Enseignant</li>
              <li class="breadcrumb-item active" aria-current="page">Liste</li>
            </ol>
            
          </nav>
        </div>
        <div class='col-lg-6 col-5 text-right'>
    <button id="exportButton" class="btn btn-sm btn-neutral  btn-primary" ><a href="{% url 'export_enseignants' %}">Exporter en Excel</a></button>
    
<button type="submit" class="btn btn-sm btn-neutral btn-primary"  ><a href="{% url 'ajouter_enseignant' %}">Ajouter</a></button>
  </div>
      </div>
    </div>
    <div class="text-center"> 
      <h2 class="h2 text-white d-inline-block mb-0">LISTE DES ENSEIGNANTS CHERCHEURS  </h2>
    </div>
    <div class="text-center"> 
      <h2 class="h2 text-white d-inline-block mb-0">Nombres Total: {{ nombre_enseignants }} </h2>
    </div>
  </div>
</div>

  
<!-- templates/home/categorie/liste_categories.html -->

 
<div class="container-fluid mt--6">
  <div class="row">
    <div class="col-xl-4 order-xl">
     
        </div>
      </div>
    </div>
<div class="col-xl-12 order-xl-5">
<div class="card">
<!-- Formulaire d'ajout -->
<div class="table-container">
  <div class="table-responsive">
        <table class="table table-striped">
          <thead class="thead-dark">
              <tr>
                  <th class="text-center">Photo</th>
                  <th class="text-center">Nom</th>
                  <th class="text-center">Prénom</th>
                  <th class="text-center">Sexe</th>
                  <th class="text-center">IM</th>
                  <th class="text-center">Date <br> Naissance</th>
                  <th class="text-center">Diplôme</th>
                  <th class="text-center">Corps</th>
                  <th class="text-center">Poste d'affectation</th>
                  <th class="text-center">Etablissements</th>
                  <th class="text-center">Situation</th>
                  <th class="text-center">Date d'entre</th>
                  <th class="text-center">grade</th>
                  
                  <th class="text-center">action</th>
              </tr>
          </thead>
          <tbody>
              {% for enseignant in enseignants %}
              <tr>
                
                  <td class="text-center  search-column"><a href="{% url 'enseignant_profile' enseignant.id %}"><img src="{{ enseignant.image.url }}" alt="{{ enseignant.nom_en }}"  class="avatar avatar-sm rounded-circle"></a></td> <!-- Insérer la photo ici -->
                  <td class="search-column">{{ enseignant.nom_en }}</td>
                  <td class="search-column">{{ enseignant.prenom_en }}</td>
                  <td class="text-center search-column">{{ enseignant.get_sex_display }}</td>
                  <td class="text-center search-column">{{ enseignant.im }}</td>
                  <td class="text-center search-column">{{ enseignant.date_nais }}</td>
                  <td class="text-center search-column">{{ enseignant.diplome.type_dip }}</td>
                  <td class="text-center search-column">{{ enseignant.corps.nom_cr }}</td>
                  <td class="text-center search-column">{{ enseignant.mention.nom_me }}</td>
                  <td class="text-center search-column">{{ enseignant.departement.nom_dep }}</td>
                  <td class="text-center search-column">{{ enseignant.situation.type_st }}</td>
                  <td class="text-center search-column">{{ enseignant.date_PF }}</td>
                  <td class="text-center search-column">{{ enseignant.grade.num_classe }}C{{ enseignant.grade.num_echellon }}E</td>
                
                  
                  <td class="text-center">
                   <div class="row">
                  
                        <a class="btn btn-primary btn-sm" href="{% url 'modifier_enseignant' enseignant.id %}">
                           <i class="fas fa-edit"></i>
                        </a>
                     
                  
                    
                    <!-- Bouton de suppression -->
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#confirmationModal{{ enseignant.id }}">
                      <i class="fas fa-trash"></i> 
                    </button>
                  </div>
                </td>
            </tr>
                <!-- Fenêtre modale de confirmation pour la suppression -->
            <div class="modal fade" id="confirmationModal{{ enseignant.id }}" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="confirmationModalLabel">Confirmation de la suppression</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    Êtes-vous sûr de vouloir supprimer cet employé?
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                    <form method="post" action="{% url 'supprimer_enseignant' enseignant.id %}">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-danger">Confirmer la suppression</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
              {% endfor %}
          </tbody>
      </table>
    </div>
  </div>
</div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
  const searchInput = document.getElementById("searchInput");
  const rows = document.querySelectorAll("tbody tr");

  searchInput.addEventListener("input", function() {
      const query = searchInput.value.trim().toLowerCase();

      rows.forEach(function(row) {
          const cells = row.querySelectorAll(".search-column");
          let rowMatch = false;

          cells.forEach(function(cell) {
              const cellText = cell.textContent.toLowerCase();
              if (cellText.includes(query)) {
                  rowMatch = true;
              }
          });

          if (rowMatch) {
              row.style.display = "table-row";
          } else {
              row.style.display = "none";
          }
      });
  });
});
</script>

  
  
      

  





 
 
   
{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script src="/static/assets/vendor/chart.js/dist/Chart.min.js"></script>
  <script src="/static/assets/vendor/chart.js/dist/Chart.extension.js"></script>
  <script src="/static/assets/vendor/sweetalert2/dist/sweetalert2.all.min.js"></script>
 
  <script>
   {% for msg in messages %}
   swal("{{ msg }}");
   {% endfor %}
  </script>
  

  
  

{% endblock javascripts %}